### ISSUE TITLE
FATA[0077] create repo failed: sql: unknown driver "sqlite3" (forgotten import?)

### ISSUE THREAD

**Issue by NatoBoram** [textileio/desktop#14]
I tried to log-in, but when I entered my mnemonics, it crashed with the following message.

```bash
FATA[0077] create repo failed: sql: unknown driver "sqlite3" (forgotten import?)
```

```yaml
OS: Ubuntu 18.04.2 LTS x86_64 
Kernel: 4.18.0-18-generic 
Uptime: 1 hour, 28 mins 
Packages: 1955 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: Unity 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 5052MiB / 7920MiB 
```
